services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "9696:9696"
    volumes:
      - /srv/docker/prowlarr:/config
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9696/ || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "7878:7878"
    volumes:
      - /srv/docker/radarr:/config
      - /mnt/media:/media
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7878/ || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "8989:8989"
    volumes:
      - /srv/docker/sonarr:/config
      - /mnt/media:/media
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8989/ || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "6767:6767"
    volumes:
      - /srv/docker/bazarr/config:/config
      - /mnt/media:/media
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6767/ || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992"
      - "44"
    volumes:
      - /srv/docker/jellyfin/config:/config
      - /srv/docker/jellyfin/cache:/cache
      - /mnt/media:/media
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8096/health || exit 1"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Madrid
    ports:
      - "5055:5055"
    volumes:
      - /srv/docker/seerr/config:/config
      - /srv/docker/seerr/cache:/cache
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
