version: "3.8"
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TOKEN=e9f2ab52727f58854ffffd06bfed7c647a899c4da205fa8340c6d07968594034
      - TECHNOLOGY=NordLynx
      - CONNECT=Spain
      - NETWORK=192.168.0.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "8080:8080"
      - "9865:9865"
      - "6881:6881"
      - "6881:6881/udp"
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.3
    container_name: qbittorrent
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=Europe/Madrid
      - WEBUI_PORT=9865
      - TORRENTING_PORT=6881
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume2/media/downloads:/downloads
    restart: unless-stopped
